// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLXHPsHozGnDSnFuzkA2maZXhyi2YNE4',
    appId: '1:976032084150:web:8d9c739ad1cccb118db617',
    messagingSenderId: '976032084150',
    projectId: 'tradehub-43a72',
    authDomain: 'tradehub-43a72.firebaseapp.com',
    storageBucket: 'tradehub-43a72.appspot.com',
    measurementId: 'G-171T4MX3N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_eQakQSmBJwzV0l_Qm32fWsR0oEBrHM',
    appId: '1:976032084150:android:68b178c58876e26d8db617',
    messagingSenderId: '976032084150',
    projectId: 'tradehub-43a72',
    storageBucket: 'tradehub-43a72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYTgICFeyl-V2iClidc1-1suXYe_OcJw',
    appId: '1:976032084150:ios:7e7e4200565957618db617',
    messagingSenderId: '976032084150',
    projectId: 'tradehub-43a72',
    storageBucket: 'tradehub-43a72.appspot.com',
    iosBundleId: 'com.example.tradeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlYTgICFeyl-V2iClidc1-1suXYe_OcJw',
    appId: '1:976032084150:ios:63d4635a86fade088db617',
    messagingSenderId: '976032084150',
    projectId: 'tradehub-43a72',
    storageBucket: 'tradehub-43a72.appspot.com',
    iosBundleId: 'com.example.tradeHub.RunnerTests',
  );
}
